export const CONSTANTS = {
  HIGHEST_MOVIES_URL: `${import.meta.env.VITE_BACKEND_URL}movies/highest-rated/page/`,
  LATEST_MOVIES_URL: `${import.meta.env.VITE_BACKEND_URL}movies/latest/page/`,
  CAROUSEL_URL: `${import.meta.env.VITE_BACKEND_URL}movies/home-carousel`,
  MOVIE_URL: `${import.meta.env.VITE_BACKEND_URL}movies/`,
  SEARCH_MOVIES_URL: `${import.meta.env.VITE_BACKEND_URL}movies/search/advanced`,
  QUERY_KEY_TAGS: ['movies'],
  HOME_CAROUSEL_QUERY_KEY: 'home-carousel',
  LATEST_MOVIES_QUERY_KEY: 'latest-movies',
  HIGHEST_RATED_MOVIES_QUERY_KEY: 'highest-rated-movies',
  MOVIE_QUERY_KEY: 'movie',
  MIN_VOTES_OPTIONS: [
    20000, 15000, 10000, 9000, 8000, 7000, 6000, 5000, 4000, 3000, 2000, 500,
    100,
  ],
  GENRE_OPTIONS: [
    'Action',
    'Adventure',
    'Animation',
    'Comedy',
    'Crime',
    'Documentary',
    'Drama',
    'Family',
    'Fantasy',
    'History',
    'Horror',
    'Music',
    'Mystery',
    'Romance',
    'Science Fiction',
    'TV Movie',
    'Thriller',
    'War',
    'Western',
  ],
  RUN_TIME_OPTIONS: [
    { label: 'Any runtime', value: '' },
    { label: '1 hour - 1.5 hours', value: '1-1.5h' },
    { label: '1.5 hours - 2 hours', value: '1.5-2h' },
    { label: '2 hours - 3 hours', value: '2-3h' },
    { label: 'More than 3 hours', value: 'over 3h' },
  ],
};
